# News Agent Configuration
# This file contains all configuration settings for the news agent
# Copy this file to config.local.yaml and update with your actual API keys

# API Keys and Authentication
api_keys:
  openai_api_key: "your_openai_api_key_here"
  anthropic_api_key: "your_anthropic_api_key_here"
  google_api_key: "your_google_api_key_here"
  brave_api_key: "your_brave_api_key_here"
  tavily_api_key: "your_tavily_api_key_here"
  aws_access_key_id: ""
  aws_secret_access_key: ""
  langchain_api_key: "your_langchain_api_key_here"
  llamaindex_api_key: "your_llamaindex_api_key_here"
  langfuse_public_key: "your_langfuse_public_key_here"
  langfuse_secret_key: "your_langfuse_secret_key_here"

# Model Configuration
models:
  provider: "openai"
  name: "gpt-5-mini-2025-08-07"

# Embedding Configuration
embeddings:
  provider: "ollama"
  model_name: "bge-large"

# News Agent Specific Settings
news_agent:
  topics_file: "news_agent/agents/news/topics.yaml"
  output_dir: "news_agent/agents/news/output"
  news_dest_file: null
  similarity_threshold: 0.95
  max_writing_tokens: 16000

# Langfuse Configuration
langfuse:
  enabled: false

# LangChain Configuration
langchain:
  tracing_v2: false
